[build.env]
passthrough = ["OPENSSL_STATIC", "PKG_CONFIG_ALLOW_CROSS"]

[target.x86_64-unknown-linux-musl]
pre-build = ["bash", "-lc", "apt-get update && apt-get install -y --no-install-recommends pkg-config && rm -rf /var/lib/apt/lists/*"]

[target.i686-unknown-linux-musl]
pre-build = ["bash", "-lc", "apt-get update && apt-get install -y --no-install-recommends pkg-config && rm -rf /var/lib/apt/lists/*"]

[target.aarch64-unknown-linux-musl]
pre-build = ["bash", "-lc", "apt-get update && apt-get install -y --no-install-recommends pkg-config && rm -rf /var/lib/apt/lists/*"]

[target.armv7-unknown-linux-musleabihf]
pre-build = ["bash", "-lc", "apt-get update && apt-get install -y --no-install-recommends pkg-config && rm -rf /var/lib/apt/lists/*"]
