name: build static binary
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - Dj-Codeman-build-test-debian
    tags:
      - '*'
jobs:    
  build:
    strategy:
      fail-fast: false
      matrix:
        target: 
          - aarch64-unknown-linux-gnu
          - i686-pc-windows-gnu
          - i686-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          
    name: Build executable
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: |
          rustup target add ${{ matrix.target }}
      - name: Install ubuntu openssl dependencies
        run : |
          sudo apt-get install libssl-dev
      - name: Update Cargo
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: update
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }} --release --target-dir=/tmp
      - name: Debug missing files
        run: |
          echo "target dir:"
          ls -a /tmp/release
          echo "deps:"
          ls -a /tmp/${{ matrix.target }}/release/deps
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            /tmp/${{ matrix.target }}/release/